spring:
  application:
    name=spring-web-basic

server:
  port: 8081

logging:
  level:  # LogExample 클래스의 로그 레벨을 asap으로 설정 기본 값은 INFO 직접 레벨 지정
    com.codeit.springwebbasic.common.log.LogExample: debug
    org.springframework.web: warn # Spring패키지 Web 관련 로그 레벨을 WARN으로 설정하고싶다.
  file:
    name: /Users/milk/Desktop/Codeit-7th-develop/logs/app.log






springdoc:
  swagger-ui:
    path: /api-docs-ui.html # UI page 경로
    tags-sorter: method # 태그 정렬 방식 (알파벳 순)
    operations-sorter: method # 메서드 정렬 방식
    display-request-duration: true # 요청 시간 표시
    doc-expansion: none # 문서 확장 방식 (none, list, full)


  api-docs:
    enabled: true
    path: /my-api# Swagger가 우리 API의 정보를 얻어 오기 위해서 요청하는 url

